In [29]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.feature_extraction import DictVectorizer
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import jieba
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import VarianceThreshold
from sklearn.decomposition import PCA

In [30]:
vector=CountVectorizer()
res=vector.fit_transform(["life is short ,i like python","life is too long,i dislike python"])
print(vector.get_feature_names())
print(res.toarray())

['dislike', 'is', 'life', 'like', 'long', 'python', 'short', 'too']
[[0 1 1 1 0 1 1 0]
 [1 1 1 0 1 1 0 1]]


In [31]:
def dictvec():
    dict=DictVectorizer()
    data=dict.fit_transform([{'city': '北京','temperature': 100}, {'city': '上海','temperature':60}, {'city': '深圳','temperature': 30}])
    print(dict.get_feature_names())
    print(dict.inverse_transform(data))
    print(data)
    return None

In [32]:
def cutword():
    con1 = jieba.cut("今天很残酷，明天更残酷，后天很美好，但绝对大部分是死在明天晚上，所以每个人不要放弃今天。")

    con2 = jieba.cut("我们看到的从很远星系来的光是在几百万年之前发出的，这样当我们看到宇宙时，我们是在看它的过去。")

    con3 = jieba.cut("如果只用一种方式了解某样事物，你就不会真正了解它。了解事物真正含义的秘密取决于如何将其与我们所了解的事物相联系。")
     # 转换成列表
    content1 = list(con1)
    content2 = list(con2)
    content3 = list(con3)

    # 吧列表转换成字符串
    c1 = ' '.join(content1)
    c2 = ' '.join(content2)
    c3 = ' '.join(content3)
    return c1,c2,c3

In [33]:
def countvec():
    cv=CountVectorizer()
    data=cv.fit_transform(["life is short ,i like python","life is too long,i dislike python"])
    print(cv.get_feature_names())
    print(data)
    print(data.toarray())
    return None

In [34]:
def hanzivec():
    #中文特征值化
    c1,c2,c3=cutword()
    print(c1,c2,c3)
    hz=CountVectorizer()
    data=hz.fit_transform([c1,c2,c3])
    print(hz.get_feature_names())
    print(data)
    print(data.toarray())
    return None

In [35]:
def tfidfvec():
    c1,c2,c3=cutword()
    tf=TfidfVectorizer()
    data=tf.fit_transform([c1,c2,c3])
    print(tf.get_feature_names())
    print(data.toarray())
    return None

In [36]:
def mm():
    #归一化
    mm=MinMaxScaler(feature_range=(0,1))
    data=mm.fit_transform([[90,2,10,40],[60,4,15,45],[75,3,13,46]])
    print(data)
    return None
    

In [37]:
#标准化
def ss():
    ss=StandardScaler()
    data=ss.fit_transform([[ 1., -1., 3.],[ 2., 4., 2.],[ 4., 6., -1.]])
    print(data)
    return None

In [38]:
#处理缺失值
def im():
    im=SimpleImputer(missing_values=np.nan,strategy="mean")
    data=im.fit_transform([[1, 2], [np.nan, 3], [7, 6]])
    print(data)
    return None

In [39]:
#处理特征值，删除低方差的特征
def vt1():
    vt=VarianceThreshold(threshold = 0.0)
    data=vt.fit_transform([[0, 2, 0, 3], [0, 1, 4, 3], [0, 1, 1, 3]])
    print(data)
    return None

In [40]:
#特征降维
def jw():
    vt=PCA(n_components=0.9)
    data=vt.fit_transform([[2,8,4,5],[6,3,0,8],[5,4,9,1]])
    print(data)
    return None

In [41]:
if __name__ == "__main__":
    jw()
    

[[-3.13587302e-16  3.82970843e+00]
 [-5.74456265e+00 -1.91485422e+00]
 [ 5.74456265e+00 -1.91485422e+00]]
