In [13]:
import torch
import numpy as np

In [2]:
x=torch.empty(5,3)
print(x)

tensor([[-9.2742e-13,  8.5759e-43, -9.2742e-13],
        [ 8.5759e-43, -9.2740e-13,  8.5759e-43],
        [-9.2740e-13,  8.5759e-43, -9.2812e-13],
        [ 8.5759e-43, -9.2812e-13,  8.5759e-43],
        [-9.2739e-13,  8.5759e-43, -9.2739e-13]])


In [3]:
x=torch.rand(5,3)
print(x)

tensor([[0.0468, 0.3939, 0.8362],
        [0.8318, 0.6716, 0.8777],
        [0.0298, 0.1996, 0.3228],
        [0.4569, 0.1219, 0.6933],
        [0.0109, 0.8881, 0.7400]])


In [4]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x=torch.tensor([5,5,3])
print(x)

tensor([5, 5, 3])


In [6]:
x=x.new_ones(5,3,dtype=torch.float64)
print(x)

x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0404,  0.4834,  1.3674],
        [-0.5103,  1.0270, -0.1905],
        [-0.0113, -0.7417,  0.9698],
        [-0.3162,  1.5056, -0.9754],
        [-0.0096, -1.1619,  2.2878]])


print(x.size())
print(x.shape)

In [7]:
y=x.view(15)
z=x.view(-1,5)
print(x.size(),y.size(),z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [8]:
x+=1
print(x)
print(y)

tensor([[ 1.0404,  1.4834,  2.3674],
        [ 0.4897,  2.0270,  0.8095],
        [ 0.9887,  0.2583,  1.9698],
        [ 0.6838,  2.5056,  0.0246],
        [ 0.9904, -0.1619,  3.2878]])
tensor([ 1.0404,  1.4834,  2.3674,  0.4897,  2.0270,  0.8095,  0.9887,  0.2583,
         1.9698,  0.6838,  2.5056,  0.0246,  0.9904, -0.1619,  3.2878])


In [9]:
x_cp=x.clone().view(15)
x-=10
print(x)
print(x_cp)

tensor([[ -8.9596,  -8.5166,  -7.6326],
        [ -9.5103,  -7.9730,  -9.1905],
        [ -9.0113,  -9.7417,  -8.0302],
        [ -9.3162,  -7.4944,  -9.9754],
        [ -9.0096, -10.1619,  -6.7122]])
tensor([ 1.0404,  1.4834,  2.3674,  0.4897,  2.0270,  0.8095,  0.9887,  0.2583,
         1.9698,  0.6838,  2.5056,  0.0246,  0.9904, -0.1619,  3.2878])


In [10]:
111

111

aaa


In [11]:
x=torch.arange(1,3).view(1,2)
print(x)
y=torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [12]:
a=torch.ones(5)
b=a.numpy()
print(a,b)

a+=1
print(a,b)
b+=1
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [15]:
a=np.ones(5)
b=torch.from_numpy(a)
print(a,b)

a+=1
print(a,b)

b+=1
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [16]:
c=torch.tensor(a)
a+=1
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [17]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))
    

tensor([[2, 3]], device='cuda:0')
tensor([[2., 3.]], dtype=torch.float64)
